CREATE TABLE IF NOT EXISTS "cities" (
  "city_id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cities_city_id_seq"),
  "city" varchar(100) NOT NULL,
  "latitude" double precision,
  "longitude" double precision,
  "address_type" varchar(50)
);