CREATE TABLE IF NOT EXISTS "weather_cities" (
  "id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "date" DATE NOT NULL,
  "city_id" smallint NOT NULL,
  "weather_code_mean" DOUBLE PRECISION,
  "temperature_min_mean" DOUBLE PRECISION,
  "temperature_max_mean" DOUBLE PRECISION,
  "precipitation_sum" DOUBLE PRECISION
);

-- add constraint unique data, city_id
ALTER TABLE "weather_cities" ADD CONSTRAINT "unique_data_city_id" UNIQUE ("date", "city_id");
